### ISSUE TITLE
Support notification attribute (prefer over output) and include playbook attr in notifications

### ISSUE THREAD

**Issue by tomashejatko** [blufor/notifu#2]
(move from prozeta/notifu)

notifcation attribute : https://sensuapp.org/docs/0.25/reference/plugins.html#check-definition-attributes

playbook : https://sensuapp.org/docs/0.25/reference/checks.html#example

**Comment by blufor** [comment]
ACK ;) will be in 1.6 (hopefully this weekend)

**Comment by blufor** [comment]
implemented in ```v1.6.0```
